### ISSUE TITLE
Index clamp bug

### ISSUE THREAD

**Issue by automan000** [TolgaOk/Differentiable-Hard-Attention-Module#2]
Greetings.
Could you fix the bug in [this file](https://github.com/TolgaOk/Differentiable-Hard-Attention-Module/blob/master/dham.py#L88)?
It should be "y_raw_ind = ((y_raw_ind + 1)*(Y/2)).clamp(0, Y-1)"
When Y > X, it will cause a cropping error.

**Comment by TolgaOk** [comment]
Hi, thanks for noticing this bug. I fixed that line.
