### ISSUE TITLE
Citing this work

### ISSUE THREAD

**Issue by georgeKillick90** [TolgaOk/Differentiable-Hard-Attention-Module#3]
Hi, I was wondering what the best way to cite this work is as I'm writing a paper where this work is relevant.

Cheers

**Comment by TolgaOk** [comment]
Hi there,

Thank you for your interest in citing this project. I included a citation file in the repository, and you can cite it using the citation widget on the homepage.

![CitationWidget](https://i.stack.imgur.com/1mdxg.png)
